# Generated by Django 6.1.1 on 2026-09-14 02:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome Completo')),
                ('cpf', models.CharField(max_length=14, unique=True, verbose_name='CPF')),
                ('cep', models.CharField(max_length=9, verbose_name='CEP')),
                ('endereco', models.CharField(max_length=250, verbose_name='Endereço')),
                ('cidade', models.CharField(max_length=100, verbose_name='Cidade')),
            ],
        ),
        migrations.CreateModel(
            name='Processo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_processo', models.CharField(max_length=30, unique=True, verbose_name='Número do Processo')),
                ('status', models.CharField(choices=[('Ativo', 'Ativo'), ('Suspenso', 'Suspenso'), ('Encerrado', 'Encerrado')], default='Ativo', max_length=20, verbose_name='Status')),
                ('descricao', models.TextField(verbose_name='Descrição / Assunto')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='Data de Abertura')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cliente', verbose_name='Cliente')),
            ],
        ),
    ]
